-- PUBLIC.MAIL_HOST definition

-- Drop table

-- DROP TABLE MAIL_HOST;

CREATE TABLE MAIL_HOST (
	NAME CHARACTER VARYING(255) NOT NULL,
	DEAD BOOLEAN DEFAULT FALSE NOT NULL,
	CONSTRAINT MAIL_HOST_PK PRIMARY KEY (NAME)
);
CREATE UNIQUE INDEX PRIMARY_KEY_6 ON MAIL_HOST (NAME);


-- PUBLIC.MAIL_SERVICE definition

-- Drop table

-- DROP TABLE MAIL_SERVICE;

CREATE TABLE MAIL_SERVICE (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING(255),
	CONSTRAINT MAIL_SERVICE_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_F ON MAIL_SERVICE (ID);


-- PUBLIC.ADDRESS_USER definition

-- Drop table

-- DROP TABLE ADDRESS_USER;

CREATE TABLE ADDRESS_USER (
	IP CHARACTER VARYING(128) NOT NULL,
	SERVICE BIGINT NOT NULL,
	CONSTRAINT ADDRESS_USER_PK PRIMARY KEY (SERVICE,IP),
	CONSTRAINT MX_USER_FK PRIMARY KEY (SERVICE),
	CONSTRAINT MX_USER_FK FOREIGN KEY (SERVICE) REFERENCES MAIL_SERVICE(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX MX_USER_FK_INDEX_8 ON ADDRESS_USER (SERVICE);
CREATE UNIQUE INDEX PRIMARY_KEY_9 ON ADDRESS_USER (IP,SERVICE);


-- PUBLIC.MAIL_DOMAIN definition

-- Drop table

-- DROP TABLE MAIL_DOMAIN;

CREATE TABLE MAIL_DOMAIN (
	NAME CHARACTER VARYING(255) NOT NULL,
	DISPOSABLE BOOLEAN DEFAULT FALSE NOT NULL,
	DEAD BOOLEAN DEFAULT FALSE NOT NULL,
	DEAD_REASON CHARACTER VARYING(255),
	SERVICE BIGINT,
	CONSTRAINT MAIL_DOMAIN_FK PRIMARY KEY (SERVICE),
	CONSTRAINT MAIL_DOMAIN_PK PRIMARY KEY (NAME),
	CONSTRAINT MAIL_DOMAIN_FK FOREIGN KEY (SERVICE) REFERENCES MAIL_SERVICE(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX MAIL_DOMAIN_FK_INDEX_7 ON MAIL_DOMAIN (SERVICE);
CREATE UNIQUE INDEX PRIMARY_KEY_D ON MAIL_DOMAIN (NAME);


-- PUBLIC.MX definition

-- Drop table

-- DROP TABLE MX;

CREATE TABLE MX (
	MAIL_DOMAIN CHARACTER VARYING(255) NOT NULL,
	MX CHARACTER VARYING(255) NOT NULL,
	CONSTRAINT MX_FK PRIMARY KEY (MAIL_DOMAIN),
	CONSTRAINT MX_FK2 PRIMARY KEY (MX),
	CONSTRAINT MX_FK FOREIGN KEY (MAIL_DOMAIN) REFERENCES MAIL_DOMAIN(NAME) ON DELETE CASCADE ON UPDATE RESTRICT,
	CONSTRAINT MX_FK2 FOREIGN KEY (MX) REFERENCES MAIL_HOST(NAME) ON DELETE CASCADE ON UPDATE RESTRICT
);
CREATE INDEX MX_FK2_INDEX_D ON MX (MX);
CREATE INDEX MX_FK_INDEX_D ON MX (MAIL_DOMAIN);


-- PUBLIC.MX_IP definition

-- Drop table

-- DROP TABLE MX_IP;

CREATE TABLE MX_IP (
	MX CHARACTER VARYING(255) NOT NULL,
	IP CHARACTER VARYING(128) NOT NULL,
	CONSTRAINT MX_IP_FK PRIMARY KEY (MX),
	CONSTRAINT MX_IP_FK FOREIGN KEY (MX) REFERENCES MAIL_HOST(NAME) ON DELETE CASCADE ON UPDATE RESTRICT
);
CREATE INDEX MX_IP_FK_INDEX_4 ON MX_IP (MX);


-- PUBLIC.MX_USER definition

-- Drop table

-- DROP TABLE MX_USER;

CREATE TABLE MX_USER (
	MX CHARACTER VARYING(255) NOT NULL,
	SERVICE BIGINT NOT NULL,
	CONSTRAINT MX2_USER_FK PRIMARY KEY (SERVICE),
	CONSTRAINT MX3_USER_FK PRIMARY KEY (MX),
	CONSTRAINT MX2_USER_FK FOREIGN KEY (SERVICE) REFERENCES MAIL_SERVICE(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT MX3_USER_FK FOREIGN KEY (MX) REFERENCES MAIL_HOST(NAME) ON DELETE CASCADE ON UPDATE RESTRICT
);
CREATE INDEX MX2_USER_FK_INDEX_8 ON MX_USER (SERVICE);
CREATE INDEX MX3_USER_FK_INDEX_8 ON MX_USER (MX);